services:
    metamodels.attribute_combinedvalues.backend_listner.get_options:
        class: MetaModels\AttributeCombinedValuesBundle\EventListener\GetOptionsListener
        arguments:
          - '@metamodels.factory'
          - '%metamodels.system_columns%'
        tags:
          - {
              name: kernel.event_listener,
              event: 'men-at-work.multi-column-wizard-bundle.get-options',
              method: getOptions
            }
